### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TheFaik** [Strafbefehl/DeluxeHubReloaded#4]
```
[10:06:42 WARN]: java.lang.IllegalArgumentException: Can not set net.minecraft.world.item.component.ResolvableProfile field org.bukkit.craftbukkit.inventory.CraftMetaSkull.profile to com.mojang.authlib.GameProfile
[10:06:42 WARN]:        at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:228)
[10:06:42 WARN]:        at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:232)
[10:06:42 WARN]:        at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.set(MethodHandleObjectFieldAccessorImpl.java:115)
[10:06:42 WARN]:        at java.base/java.lang.reflect.Field.set(Field.java:836)
[10:06:42 WARN]:        at DeluxeHubReloaded-3.6.3.jar//fun.lewisdev.deluxehub.hook.hooks.head.BaseHead.getHead(BaseHead.java:37)
[10:06:42 WARN]:        at DeluxeHubReloaded-3.6.3.jar//fun.lewisdev.deluxehub.utility.ItemStackBuilder.getItemStack(ItemStackBuilder.java:37)
[10:06:42 WARN]:        at DeluxeHubReloaded-3.6.3.jar//fun.lewisdev.deluxehub.utility.ItemStackBuilder.getItemStack(ItemStackBuilder.java:87)
[10:06:42 WARN]:        at DeluxeHubReloaded-3.6.3.jar//fun.lewisdev.deluxehub.inventory.inventories.CustomGUI.onEnable(CustomGUI.java:34)
[10:06:42 WARN]:        at java.base/java.util.HashMap$Values.forEach(HashMap.java:1074)
[10:06:42 WARN]:        at DeluxeHubReloaded-3.6.3.jar//fun.lewisdev.deluxehub.inventory.InventoryManager.onEnable(InventoryManager.java:29)
[10:06:42 WARN]:        at DeluxeHubReloaded-3.6.3.jar//fun.lewisdev.deluxehub.DeluxeHubPlugin.onEnable(DeluxeHubPlugin.java:95)
[10:06:42 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[10:06:42 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[10:06:42 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[10:06:42 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519)
[10:06:42 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:660)
[10:06:42 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:609)
[10:06:42 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:742)
[10:06:42 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:504)
[10:06:42 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:378)
[10:06:42 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1216)
[10:06:42 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[10:06:42 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1575)
```

**Comment by Strafbefehl** [comment]
Hello, can you maybe provide more information than only the error log?

- Server Version
- Which Jar did you use?
- Which Plugin Version you are using?
- How does the error happend?

**Comment by TheFaik** [comment]
> Здравствуйте, можете ли вы предоставить больше информации, чем только журнал ошибок?
> 
>     * Версия сервера
> 
>     * Какой Jar вы использовали?
> 
>     * Какую версию плагина вы используете?
> 
>     * Как происходит ошибка?

1. 1.21.1 
2. Leaf (latest) (fork purpur & gale)
3. 3.6.3
4. Immediately after starting the server

This started after the Bukkit update, after which paper added patches to their jar.

**Comment by TheFaik** [comment]
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/8d52226914ce4b99f35be3d6954f35616d92476d#src/main/java/org/bukkit/craftbukkit/inventory/CraftMetaSkull.java

**Comment by Strafbefehl** [comment]
Did you downloaded the right jar? Because there are 3 different jars

https://github.com/Strafbefehl/DeluxeHubReloaded/releases/download/v3.6.3/DeluxeHubReloaded-1.21-1.21.1-3.6.3.jar

**Comment by Strafbefehl** [comment]
I am closing this issue as you have not replied. Have a nice day!

**Comment by TheFaik** [comment]
> Вы скачали правильный jar? Потому что есть 3 разные баночки
> 
> [https://github.com/Strafbefehl/DeluxeHubReloaded/releases/download/v3.6.3/DeluxeHubReloaded-1.21-1.21.1-3.6.3.jar ](https://github.com/Strafbefehl/DeluxeHubReloaded/releases/download/v3.6.3/DeluxeHubReloaded-1.21-1.21.1-3.6.3.jar)

Yes. That version.

**Comment by TheFaik** [comment]
> Закрываю тему, так как вы не ответили. Хорошего дня!

I didn't receive a message, sorry.
